### 1. Obtener todos los usuarios
GET http://localhost:3000/api/v1/users

### 2. Obtener usuario por ID
GET http://localhost:3000/api/v1/users/1

### 3. Crear un nuevo usuario
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Alan Turing",
  "email": "alan@turing.org"
}

### 4. Eliminar un usuario
DELETE http://localhost:3000/api/v1/users/1